apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgpool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgpool
  template:
    metadata:
      labels:
        app: pgpool
    spec:
      containers:
        - name: pgpool
          image: bitnami/pgpool:latest
          env:
            - name: PGPOOL_BACKEND_NODES
              value: "0:postgres:5432"
            - name: PGPOOL_POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: pg-config
                  key: POSTGRES_USER
            - name: PGPOOL_POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: pg-config
                  key: POSTGRES_PASSWORD
            - name: PGPOOL_ENABLE_LOAD_BALANCING
              value: "yes"
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: pgpool
spec:
  selector:
    app: pgpool
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
